### ISSUE TITLE
listFiles

### ISSUE THREAD

**Issue by epsa-dev** [gliterd/backblaze-b2#27]
$fileList = $client->listFiles([ 'BucketId' => '6182a9b37d82f0206b8f0233' ]);
print_r($fileList);

BackblazeB2\File Object ( [id:protected] => 4_z6182a9b37d82f0206b8f061b_f100636c8f41465a9_d20190215_m224636_c002_v0001111_t0024 [name:protected] => cosas1.txt [hash:protected] => [size:protected] => 11 [type:protected] => [info:protected] => [bucketId:protected] => [action:protected] => [uploadTimestamp:protected] => )

How use json_encode($fileList); ? 😢 😭

**Comment by jewtis** [comment]
Hi!
I changed the response of $client->listFiles($bucketId)
To avoid "protected" I added to vendor/gliterd/backblaze-b2/src/Client.php at line 358:
foreach ($response['files'] as $file) {				
$filesArray[] = ['fileId'=>$file['fileId'],'fileName'=>$file['fileName'],'fileSize'=>$file['size'],'type'=>$file['contentType']];
header("Content-Type: application/json");
$filesArray=json_encode($filesArray);
global $responseArray[]=$filesArray;
So I can use one JSON object per bucket with all file-infos unprotected... 
I store these "Bucket/File-info jsons($fileArray) in a global "response-array" and echo it instead of the regular $files.	
In the Ajax function(response) i decode the response until I get the wanted Infos unprotected	
Hope it helps...
Joe

**Comment by mhetreramesh** [comment]
I don't understand whats the problem here, could you explain a bit more?

**Comment by JoachimThomas** [comment]
Hi !
epsa-dev asked how to use the response to $fileList = $client->listFiles.
All Items in the response are protected because the original response from b2 is transformed to 
File.php, so no way to use them. Thats all.
I don't understand why the file.php has protected variables.
Joe
